# Generated by Django 3.2.5 on 2023-11-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0003_auto_20231128_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dashboard_pic',
            field=models.ImageField(blank=True, upload_to='dashboard/%Y/%m/%d/'),
        ),
    ]
