# Generated by Django 3.2.5 on 2023-11-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0004_profile_dashboard_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_intro',
            field=models.CharField(default='my profile intro', max_length=1000),
        ),
    ]
