# Generated by Django 3.2.5 on 2023-11-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0005_profile_profile_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='favourite/%Y/%m/%d/')),
                ('description', models.CharField(default='page intro', max_length=200)),
                ('url_link', models.CharField(default='page link', max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouritePage', to='dwitter.favourite_pages'),
        ),
    ]
