# Generated by Django 3.2.5 on 2024-07-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0007_alter_profile_profile_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_intro',
        ),
    ]
