# Generated by Django 3.2.5 on 2024-07-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0008_remove_profile_profile_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dashboard_pic',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
